apiVersion: v1
kind: Service
metadata:
  namespace: jhamohneesh
  name: falcon-graph-01
  labels:
    app: jhamohneesh
spec:
  type: ClusterIP
  ports:
    - name: rpc
      port: 6070
    - name: http
      port: 6071
  selector:
    name: falcon-graph-01
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: jhamohneesh
  name: falcon-graph-01
  labels:
    app: jhamohneesh
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: falcon-graph-01
    spec:
      containers:
        - name: falcon-graph-01
          image: registry.cn-hangzhou.aliyuncs.com/jhamohneesh/graph:v0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6070
              name: rpc
              protocol: TCP
            - containerPort: 6071
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /jhamohneesh/graph/config
              name: falcon-graph-config
            - mountPath: /jhamohneesh/graph/data
              name: falcon-graph-data
            - mountPath: /etc/localtime
              name: tz-config
      volumes:
        - flexVolume:
            driver: alicloud/nas
            options:
              path: /jhamohneesh/falcon-graph/01/config
              server: xxx.cn-hangzhou.nas.aliyuncs.com
              vers: "4.0"
          name: falcon-graph-config
        - flexVolume:
            driver: alicloud/nas
            options:
              path: /jhamohneesh/falcon-graph/01/data
              server: xxx.cn-hangzhou.nas.aliyuncs.com
              vers: "4.0"
          name: falcon-graph-data
        - hostPath:
            path: /etc/localtime
            type: ''
          name: tz-config